name: ezytdl/linux pybridge dist
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      release_id:
        description: 'Release ID'
        type: string
        required: true

jobs:
  linux-dist:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        
        - name: Install python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
            cache: 'pip'
  
        - name: Install pybridge deps
          run: |
            pip install -r requirements.txt
  
        - name: Build app
          run: |
            pyinstaller bridge.py --workpath "dist/build" --specpath "dist/build" -y --name "ezytdl-ytdlp-bridge-linux" --clean --noconfirm --onefile

        - name: Upload files to release_id
          uses: xresloader/upload-to-github-release@main
          with:
            release_id: ${{ inputs.release_id }}
            file: ./dist/ezytdl-ytdlp-bridge-linux*
            overwrite: true
            verbose: true
  