name: ezytdl/windows pybridge dist
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      release_id:
        description: 'Release ID'
        type: string
        required: true

jobs:
  windows-dist:
    runs-on: windows-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pybridge deps
        run: |
          pip install -r requirements.txt

      - name: Build app
        run: |
          python constants.py
          pyinstaller bridge.py --add-data "constants.json;." --workpath "dist/build" --specpath "dist/build" -y --name "bridge-win32" --clean --noconfirm --onefile
          pyinstaller bridge.py --add-data "constants.json;." --workpath "dist-zip/build" --specpath "dist-zip/build" -y --name "bridge-win32-zip" --clean --noconfirm

      - name: Bundle everything in the destination dist-zip/build/bridge-win32 folder into a ZIP with 7zip, and place that in dist/
        run: |
          cd dist-zip/build/bridge-win32
          7z a -r ./dist/bridge-win32.zip ./dist-zip/build/bridge-win32-zip/*

      - name: Upload files to release_id
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ./dist/bridge-win32*
          overwrite: true
          verbose: true
          draft: true
