name: ezytdl/macos pybridge dist
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      release_id:
        description: 'Release ID'
        type: string
        required: true

jobs:
  macos-dist:
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pybridge deps
        run: |
          pip install -r requirements.txt

      - name: Build bundled file
        run: |
          python constants.py
          pyinstaller bridge.py --add-data "constants.json:." --workpath "dist/build" --specpath "dist/build" -y --name "bridge-darwin" --clean --noconfirm --onefile
          chmod +x ./dist/bridge-darwin
          node test "./dist/bridge-darwin"

      - name: Upload bundled file
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ./dist/bridge-darwin
          overwrite: true
          verbose: true
          draft: true

      - name: Build zip
        run: |
          rm ./dist/bridge-darwin
          pyinstaller bridge.py --add-data "constants.json:." --workpath "dist/build" --specpath "dist/build" -y --name "bridge-darwin" --clean --noconfirm
          chmod +x ./dist/bridge-darwin/bridge-darwin
          node test "./dist/bridge-darwin/bridge-darwin"
          cd ./dist/bridge-darwin/
          zip -r ../bridge-darwin.zip *
          cd ../../

      - name: Upload zip
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ./dist/bridge-darwin.zip
          overwrite: true
          verbose: true
          draft: true
