name: ezytdl/windows pybridge dist
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      release_id:
        description: 'Release ID'
        type: string
        required: true

jobs:
  windows-dist:
    runs-on: windows-latest

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pybridge deps
        run: |
          pip install -r requirements.txt

      - name: Build bundled file
        run: |
          python constants.py
          pyinstaller bridge.py --add-data "constants.json;." --workpath "dist/build" --specpath "dist/build" -y --name "bridge-win32" --clean --noconfirm --onefile
          node test "./dist/bridge-win32.exe"

      - name: Upload bundled file
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ./dist/bridge-win32.exe
          overwrite: true
          verbose: true
          draft: true

      - name: Build zip
        run: |
          pyinstaller bridge.py --add-data "constants.json;." --workpath "dist/build" --specpath "dist/build" -y --name "bridge-win32" --clean --noconfirm
          node test "./dist/bridge-win32/bridge-win32.exe"
          7z a -r ./dist/bridge-win32.zip ./dist/bridge-win32/*

      - name: Upload zip
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ./dist/bridge-win32.zip
          overwrite: true
          verbose: true
          draft: true
