name: ezytdl/linux pybridge dist
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_call:
    inputs:
      tag:
        description: 'Release Tag'
        type: string
        required: true

jobs:
  linux-dist:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        
        - name: Install python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
            cache: 'pip'
  
        - name: Install pybridge deps
          run: |
            pip install -r requirements.txt
  
        - name: Build app
          run: |
            pyinstaller bridge.py --workpath "dist/build" --specpath "dist/build" -y --name "ezytdl-ytdlp-bridge" --clean --noconfirm --onefile

        - name: Upload files to release_id
          uses: svenstaro/upload-release-action@v2
          with:
            tag: ${{ inputs.tag }}
            file: ./dist/ezytdl-ytdlp-bridge
            asset_name: ezytdl-ytdlp-bridge-linux
  